### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'DOWNLOAD_DIR'

### ISSUE THREAD

**Issue by johnjansen** [babilen/wp-download#11]
now, this might be 100% user error, and i'll admit to spending very little time on this, however ...

1) I have a hacked fork to sidestep https://github.com/babilen/wp-download/issues/9, which you will note in the next step (DIFF https://github.com/johnjansen/wp-download/commit/9a161d995f6612dd91d1a27fd605159f64813b7b)
2) a Dockerfile

    FROM python:2.7.10

    RUN pip install --upgrade pip
    RUN pip install progressbar
    RUN pip install https://github.com/johnjansen/wp-download/zipball/master

    ADD wpdownloadrc /root/.wpdownloadrc

    RUN mkdir /wikipedia
    CMD wp-download --resume -v /wikipedia

3) a problem

    Traceback (most recent call last):
      File "/usr/local/bin/wp-download", line 183, in <module>
        download_path = os.path.abspath(args.DOWNLOAD_DIR)
    AttributeError: 'Namespace' object has no attribute 'DOWNLOAD_DIR'

Anyone got this working in its current for (Docker excluded)?

**Comment by babilen** [comment]
Could you try rebasing against current HEAD? It this issue should have been fixed in https://github.com/babilen/wp-download/commit/020096f2bb39721e73564e20f4409c1523c3b71b
