### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by xxmarijnw** [babilen/wp-download#13]
When trying to download dumps from the Dutch Wikipedia I get the following:

`
Traceback (most recent call last):
  File "/usr/local/bin/wp-download", line 580, in <module>
    WP_DOWN.download_all_languages(DOWNLOAD_PATH)
  File "/usr/local/bin/wp-download", line 429, in download_all_languages
    self.download_language(lang, path)
  File "/usr/local/bin/wp-download", line 416, in download_language
    self._create_download_dirs(language, path)
  File "/usr/local/bin/wp-download", line 292, in _create_download_dirs
    down_dir = self._download_directory(language, path)
  File "/usr/local/bin/wp-download", line 281, in _download_directory
    language).strftime('%Y%m%d'))
  File "/usr/local/bin/wp-download", line 513, in latest_dump_date
    return max(self.dump_dates(self.language_url(language)))
ValueError: max() arg is an empty sequence
`
([Hastebin](http://hastebin.com/hucehajite.rb))

Using the following configuration file:
[Hastebin](http://hastebin.com/apisosuqeb.vala)

Update 1: I have read this, but there isn't any solution given.
Update 2: The error has been fixed. I had to reinstall it, this time using install.py instead of pip.

**Comment by xxmarijnw** [comment]
Update: This error has been resolved after reading [this](https://github.com/babilen/wp-download/issues/6). This may be closed. Thank you!

**Comment by xxmarijnw** [comment]
Update: I have read [this](https://github.com/babilen/wp-download/issues/6), but there isn't any solution given.

**Comment by babilen** [comment]
Yeah, the code in the repository is newer than what you'd find in the cheeseshop. I would recommend installing from git checkouts using setup.py for now.

**Comment by xxmarijnw** [comment]
@babilen You should probably mention that in the readme ;)
